# Generated by Django 4.1.4 on 2023-01-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('game_state', models.CharField(choices=[('WA', 'Waiting'), ('PL', 'Playing'), ('EN', 'Ended')], default='WA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('device', models.CharField(choices=[('DE', 'Desktop'), ('MO', 'Mobile')], max_length=2)),
                ('is_room_owner', models.BooleanField(default=False)),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.room')),
            ],
        ),
    ]
